### ISSUE TITLE
connections to program

### ISSUE THREAD

**Issue by RawLiquid** [JanneMantyharju/apm-hss-emulator#1]
Is it just me, or is there no way to program the chip while it is on the board?

**Comment by RawLiquid** [comment]
Nevermind, I think I  had a brain fart...Only needs serial access to reprogram as long as the chip already has the bootloader... I was thinking the ICSP header was required...

**Comment by JanneMantyharju** [comment]
Yes, I have test socket for avr chips, which I use to burn the bootloader in them before soldering the chip to the board.
