### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by RawLiquid** [JanneMantyharju/apm-hss-emulator#2]
Hey, is so the libraries you provide call for AP_MATH, which isn't included, I've tried supplying the things it wants but that didn't help any....

**Comment by JanneMantyharju** [comment]
Thanks for reminding me about this project :-D AP_MATH comes from APM source, so you need to have it's libraries on your library path. If you get errors while compiling, try to use APM source from about the time when apm-hss-emulator source is dated. It might be that the current version is not compatible any more.
